language: python
python:
    - "3.8"
install:
    - pip install pipenv
    - pipenv install --dev
    - ./manage.py migrate
script:
    - coverage run --source='djservices' manage.py test
after_success:
    - coveralls
