language: python
python:
    - "3.8"
install:
    - pip install pipenv
    - pipenv install --dev
script:
    - ./manage.py migrate
    - coverage run --source='djservices' manage.py test tests.base
after_success:
    - coveralls
